version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - STATS-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
    - POSTGRES_DB=stats
    - POSTGRES_USER=stats
    - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm
    image: ewm
    container_name: ewm
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
