version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - STATS-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
    - POSTGRES_DB=stats
    - POSTGRES_USER=stats
    - POSTGRES_PASSWORD=stats

  ewm-service:
    build: main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - STATS_SERVICE_URL=http://stats-service:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
